framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                # Un événement peut n'intéresser personne (encore)
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
